### ISSUE TITLE
Add GUI for output channel test

### ISSUE THREAD

**Issue by seank** [malcom2073/emstune#24] opened 2016-04-08 03:19 UTC
Hi,

Can you add a small utility item to EMStune so that users can test a specified output? Basically we just need:

Channel: (0-24)
Interval: (ticks 16-b)
Runtime PW: (ticks 16-b)
Delay:   (ticks 32-b) 
Num Repeats: (8-b)

This is how the packet is deconstructed:
         BTpatternParemeterSet.simulatedTCNT = 0;
         BTpatternParemeterSet.delay = *((uint32_t *) RXBufferCurrentPosition);
         RXBufferCurrentPosition += sizeof(uint32_t);
         BTpatternParemeterSet.runtime = *((uint16_t *) RXBufferCurrentPosition);
         RXBufferCurrentPosition += sizeof(uint16_t);
         BTpatternParemeterSet.testInterval = *((uint16_t *) RXBufferCurrentPosition);
         RXBufferCurrentPosition += sizeof(uint16_t);;
         BTpatternParemeterSet.channel = *((uint8_t *) RXBufferCurrentPosition);
         RXBufferCurrentPosition += sizeof(uint8_t);
         BTpatternParemeterSet.numberOfEvents = *((uint8_t *) RXBufferCurrentPosition);

A demo packet can be found here: lib/test.packets/output.tests/output.test.CH4.interval-10mS.delay-0xFF.runtime-2mS-repeat-0x35.bin.bin

Thanks!

**Comment by seank** [comment] 2016-12-04 18:47
Bump, for all the installs in progress :-)

**Comment by seank** [comment] 2016-12-05 19:04
It would be handy to be able to scan though the channels, or maybe have a button to click that +/- the target channel.

**Comment by seank** [comment] 2016-12-14 03:03
#define OUTPUT_TEST_SEQUENCE            0x8892
Is the packet ID :)

**Comment by malcom2073** [comment] 2017-01-23 02:19
This was added in b6721e7772e88e28398b3ede3590ec5734c88860, but try the latest unstable: can you verify it works as intended?

**Comment by malcom2073** [comment] 2017-02-05 16:01
Verified as working, closing issue ticket.

**Closed by malcom2073** 2017-02-05 16:01 UTC
